# Arquivo gerado pelo MIDI-QWERTY — pode ser editado à mão.

[midi]
port = "loopMIDI Port 2"

[capture]
toggle_key = "scroll lock"

[[map]]
key = "b"
type = "cc_toggle"
channel = 1
cc = 3
on_value = 127
off_value = 0

[[map]]
key = ""
type = "cc_toggle"
channel = 0
cc = 0
on_value = 127
off_value = 0
