# Arquivo gerado pelo midi_cc — pode ser editado à mão.

[midi]
port = "loopMIDI_teste 2"

[capture]
toggle_key = "scroll lock"

[[map]]
key = "b"
type = "note"
channel = 0
note = 60
velocity = 100

[[map]]
key = "v"
type = "note"
channel = 0
note = 67
velocity = 100
